# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b917c3155c2dd5a5a19754a063eb74f71eb3c6075a585834272c51f74764c4f29b3f1d8de1828b5152ae39069d1fbfe8fcc634503f7b26960c2ac93ea3806a3

test:
  secret_key_base: 50def9d855501db3dd2e35d7502aa5df022b6b2fd72a10734ad15735ebec864b8ec2099af9d1ce3e3af703f1b03d7068182eeb0c64256197b02522856befd611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
